language: csharp
solution: LunaFramework.sln
mono: none
dotnet: 3.1.402
branches:
  only:
    - master
script:
  - dotnet build
  - dotnet test
deploy:
  provider: script
  script: bash publish2Nuget.sh $NUGET_KEY